// Generated by Apple Swift version 6.3.3 effective-5.10 (swiftlang-6.3.3.1.3 clang-2100.1.1.101)
#ifndef BLINKID_SWIFT_H
#define BLINKID_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif // defined(__OBJC__)
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef unsigned char char8_t;
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# if (defined(__cplusplus) && __cplusplus >= 201103L) ||      (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 202311L) ||      __has_feature(objc_fixed_enum)
#  define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
#  if __has_feature(generalized_swift_name)
#   define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
#  else
#   define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
#  endif
# else
#  define SWIFT_ENUM(_type, _name, _extensibility) _type _name; enum 
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM_TAG)
# if (defined(__cplusplus) && __cplusplus >= 201103L) ||      (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 202311L) ||      __has_feature(objc_fixed_enum)
#  define SWIFT_ENUM_TAG enum
# else
#  define SWIFT_ENUM_TAG
# endif
#endif
#if !defined(SWIFT_ENUM_FWD_DECL)
# if (defined(__cplusplus) && __cplusplus >= 201103L) ||      (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 202311L) ||      __has_feature(objc_fixed_enum)
#  define SWIFT_ENUM_FWD_DECL(_type, _name) enum _name : _type;
# else
#  define SWIFT_ENUM_FWD_DECL(_type, _name) typedef _type _name;
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_AVAILABILITY_DOMAIN)
# define SWIFT_AVAILABILITY_DOMAIN(dom, ...) __attribute__((availability(domain: dom, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if !__has_feature(nullability)
# define _Nonnull
# define _Nullable
# define _Null_unspecified
#elif !defined(__OBJC__)
# pragma clang diagnostic ignored "-Wnullability-extension"
#endif
#if !__has_feature(nullability_nullable_result)
# define _Nullable_result _Nullable
#endif
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="BlinkID",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__cplusplus)
extern "C" {
#endif

#if defined(__cplusplus)
} // extern "C"
#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
#endif

#endif // defined(__OBJC__)
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="BlinkID",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)

#endif // defined(__OBJC__)
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
// Allow user to find the header using additional include paths
#if __has_include(<swiftToCxx/_SwiftCxxInteroperability.h>)
#include <swiftToCxx/_SwiftCxxInteroperability.h>
// Look for the C++ interop support header relative to clang's resource dir:
//  '<toolchain>/usr/lib/clang/<version>/include/../../../swift/swiftToCxx'.
#elif __has_include(<../../../swift/swiftToCxx/_SwiftCxxInteroperability.h>)
#include <../../../swift/swiftToCxx/_SwiftCxxInteroperability.h>
#elif __has_include(<../../../../../lib/swift/swiftToCxx/_SwiftCxxInteroperability.h>)
//  '<toolchain>/usr/local/lib/clang/<version>/include/../../../../../lib/swift/swiftToCxx'.
#include <../../../../../lib/swift/swiftToCxx/_SwiftCxxInteroperability.h>
#endif
#pragma clang diagnostic pop
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
#endif

#ifdef SWIFT_SYMBOL
#undef SWIFT_SYMBOL
#endif
#define SWIFT_SYMBOL(usrValue) SWIFT_SYMBOL_MODULE_USR("BlinkID", usrValue)
#ifndef SWIFT_PRINTED_CORE
#define SWIFT_PRINTED_CORE
namespace swift SWIFT_PRIVATE_ATTR {

namespace _impl {

#ifdef __cplusplus
extern "C" {
#endif

// Swift type metadata response type.
struct MetadataResponseTy {
  void * _Null_unspecified _0;
  uint64_t _1;
};
// Swift type metadata request type.
typedef uint64_t MetadataRequestTy;

#if __cplusplus > 201402L
#  define SWIFT_NOEXCEPT_FUNCTION_PTR noexcept
#else
#  define SWIFT_NOEXCEPT_FUNCTION_PTR
#endif

using ValueWitnessInitializeBufferWithCopyOfBufferTy = void * _Nonnull(* __ptrauth_swift_value_witness_function_pointer(55882))(void * _Nonnull, void * _Nonnull, void * _Nonnull) SWIFT_NOEXCEPT_FUNCTION_PTR;
using ValueWitnessDestroyTy = void(* __ptrauth_swift_value_witness_function_pointer(1272))(void * _Nonnull, void * _Nonnull) SWIFT_NOEXCEPT_FUNCTION_PTR;
using ValueWitnessInitializeWithCopyTy = void * _Nonnull(* __ptrauth_swift_value_witness_function_pointer(58298))(void * _Nonnull, void * _Nonnull, void * _Nonnull) SWIFT_NOEXCEPT_FUNCTION_PTR;
using ValueWitnessAssignWithCopyTy = void * _Nonnull(* __ptrauth_swift_value_witness_function_pointer(34641))(void * _Nonnull, void * _Nonnull, void * _Nonnull) SWIFT_NOEXCEPT_FUNCTION_PTR;
using ValueWitnessInitializeWithTakeTy = void * _Nonnull(* __ptrauth_swift_value_witness_function_pointer(18648))(void * _Nonnull, void * _Nonnull, void * _Nonnull) SWIFT_NOEXCEPT_FUNCTION_PTR;
using ValueWitnessAssignWithTakeTy = void * _Nonnull(* __ptrauth_swift_value_witness_function_pointer(61402))(void * _Nonnull, void * _Nonnull, void * _Nonnull) SWIFT_NOEXCEPT_FUNCTION_PTR;
using ValueWitnessGetEnumTagSinglePayloadTy = unsigned(* __ptrauth_swift_value_witness_function_pointer(24816))(const void * _Nonnull, unsigned, void * _Nonnull) SWIFT_NOEXCEPT_FUNCTION_PTR;
using ValueWitnessStoreEnumTagSinglePayloadTy = void(* __ptrauth_swift_value_witness_function_pointer(41169))(void * _Nonnull, unsigned, unsigned, void * _Nonnull) SWIFT_NOEXCEPT_FUNCTION_PTR;

struct ValueWitnessTable {
  ValueWitnessInitializeBufferWithCopyOfBufferTy _Nonnull initializeBufferWithCopyOfBuffer;
  ValueWitnessDestroyTy _Nonnull destroy;
  ValueWitnessInitializeWithCopyTy _Nonnull initializeWithCopy;
  ValueWitnessAssignWithCopyTy _Nonnull assignWithCopy;
  ValueWitnessInitializeWithTakeTy _Nonnull initializeWithTake;
  ValueWitnessAssignWithTakeTy _Nonnull assignWithTake;
  ValueWitnessGetEnumTagSinglePayloadTy _Nonnull getEnumTagSinglePayload;
  ValueWitnessStoreEnumTagSinglePayloadTy _Nonnull storeEnumTagSinglePayload;
  size_t size;
  size_t stride;
  unsigned flags;
  unsigned extraInhabitantCount;

  constexpr size_t getAlignment() const { return (flags & 255) + 1; }
};

using EnumValueWitnessGetEnumTagTy = unsigned(* __ptrauth_swift_value_witness_function_pointer(41909))(const void * _Nonnull, void * _Nonnull) SWIFT_NOEXCEPT_FUNCTION_PTR;
using EnumValueWitnessDestructiveProjectEnumDataTy = void(* __ptrauth_swift_value_witness_function_pointer(1053))(void * _Nonnull, void * _Nonnull) SWIFT_NOEXCEPT_FUNCTION_PTR;
using EnumValueWitnessDestructiveInjectEnumTagTy = void(* __ptrauth_swift_value_witness_function_pointer(45796))(void * _Nonnull, unsigned, void * _Nonnull) SWIFT_NOEXCEPT_FUNCTION_PTR;

struct EnumValueWitnessTable {
  ValueWitnessTable vwTable;
  EnumValueWitnessGetEnumTagTy _Nonnull getEnumTag;
  EnumValueWitnessDestructiveProjectEnumDataTy _Nonnull destructiveProjectEnumData;
  EnumValueWitnessDestructiveInjectEnumTagTy _Nonnull destructiveInjectEnumTag;
};

#undef SWIFT_NOEXCEPT_FUNCTION_PTR


// type metadata address for Bool.
SWIFT_IMPORT_STDLIB_SYMBOL extern size_t $sSbN;
// type metadata address for Int8.
SWIFT_IMPORT_STDLIB_SYMBOL extern size_t $ss4Int8VN;
// type metadata address for UInt8.
SWIFT_IMPORT_STDLIB_SYMBOL extern size_t $ss5UInt8VN;
// type metadata address for Int16.
SWIFT_IMPORT_STDLIB_SYMBOL extern size_t $ss5Int16VN;
// type metadata address for UInt16.
SWIFT_IMPORT_STDLIB_SYMBOL extern size_t $ss6UInt16VN;
// type metadata address for Int32.
SWIFT_IMPORT_STDLIB_SYMBOL extern size_t $ss5Int32VN;
// type metadata address for UInt32.
SWIFT_IMPORT_STDLIB_SYMBOL extern size_t $ss6UInt32VN;
// type metadata address for Int64.
SWIFT_IMPORT_STDLIB_SYMBOL extern size_t $ss5Int64VN;
// type metadata address for UInt64.
SWIFT_IMPORT_STDLIB_SYMBOL extern size_t $ss6UInt64VN;
// type metadata address for Float.
SWIFT_IMPORT_STDLIB_SYMBOL extern size_t $sSfN;
// type metadata address for Double.
SWIFT_IMPORT_STDLIB_SYMBOL extern size_t $sSdN;
// type metadata address for OpaquePointer.
SWIFT_IMPORT_STDLIB_SYMBOL extern size_t $ss13OpaquePointerVN;
// type metadata address for Int.
SWIFT_IMPORT_STDLIB_SYMBOL extern size_t $sSiN;
// type metadata address for UInt.
SWIFT_IMPORT_STDLIB_SYMBOL extern size_t $sSuN;

#ifdef __cplusplus
}
#endif


} // namespace _impl


#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wc++17-extensions"
template<>
inline const constexpr bool isUsableInGenericContext<bool> = true;

template<>
struct TypeMetadataTrait<bool> {
  static SWIFT_INLINE_THUNK void * _Nonnull getTypeMetadata() {
    return &_impl::$sSbN;
  }
};

template<>
inline const constexpr bool isUsableInGenericContext<int8_t> = true;

template<>
struct TypeMetadataTrait<int8_t> {
  static SWIFT_INLINE_THUNK void * _Nonnull getTypeMetadata() {
    return &_impl::$ss4Int8VN;
  }
};

template<>
inline const constexpr bool isUsableInGenericContext<uint8_t> = true;

template<>
struct TypeMetadataTrait<uint8_t> {
  static SWIFT_INLINE_THUNK void * _Nonnull getTypeMetadata() {
    return &_impl::$ss5UInt8VN;
  }
};

template<>
inline const constexpr bool isUsableInGenericContext<int16_t> = true;

template<>
struct TypeMetadataTrait<int16_t> {
  static SWIFT_INLINE_THUNK void * _Nonnull getTypeMetadata() {
    return &_impl::$ss5Int16VN;
  }
};

template<>
inline const constexpr bool isUsableInGenericContext<uint16_t> = true;

template<>
struct TypeMetadataTrait<uint16_t> {
  static SWIFT_INLINE_THUNK void * _Nonnull getTypeMetadata() {
    return &_impl::$ss6UInt16VN;
  }
};

template<>
inline const constexpr bool isUsableInGenericContext<int32_t> = true;

template<>
struct TypeMetadataTrait<int32_t> {
  static SWIFT_INLINE_THUNK void * _Nonnull getTypeMetadata() {
    return &_impl::$ss5Int32VN;
  }
};

template<>
inline const constexpr bool isUsableInGenericContext<uint32_t> = true;

template<>
struct TypeMetadataTrait<uint32_t> {
  static SWIFT_INLINE_THUNK void * _Nonnull getTypeMetadata() {
    return &_impl::$ss6UInt32VN;
  }
};

template<>
inline const constexpr bool isUsableInGenericContext<int64_t> = true;

template<>
struct TypeMetadataTrait<int64_t> {
  static SWIFT_INLINE_THUNK void * _Nonnull getTypeMetadata() {
    return &_impl::$ss5Int64VN;
  }
};

template<>
inline const constexpr bool isUsableInGenericContext<uint64_t> = true;

template<>
struct TypeMetadataTrait<uint64_t> {
  static SWIFT_INLINE_THUNK void * _Nonnull getTypeMetadata() {
    return &_impl::$ss6UInt64VN;
  }
};

template<>
inline const constexpr bool isUsableInGenericContext<float> = true;

template<>
struct TypeMetadataTrait<float> {
  static SWIFT_INLINE_THUNK void * _Nonnull getTypeMetadata() {
    return &_impl::$sSfN;
  }
};

template<>
inline const constexpr bool isUsableInGenericContext<double> = true;

template<>
struct TypeMetadataTrait<double> {
  static SWIFT_INLINE_THUNK void * _Nonnull getTypeMetadata() {
    return &_impl::$sSdN;
  }
};

template<>
inline const constexpr bool isUsableInGenericContext<void *> = true;

template<>
struct TypeMetadataTrait<void *> {
  static SWIFT_INLINE_THUNK void * _Nonnull getTypeMetadata() {
    return &_impl::$ss13OpaquePointerVN;
  }
};

template<>
inline const constexpr bool isUsableInGenericContext<swift::Int> = true;

template<>
struct TypeMetadataTrait<swift::Int> {
  static SWIFT_INLINE_THUNK void * _Nonnull getTypeMetadata() {
    return &_impl::$sSiN;
  }
};

template<>
inline const constexpr bool isUsableInGenericContext<swift::UInt> = true;

template<>
struct TypeMetadataTrait<swift::UInt> {
  static SWIFT_INLINE_THUNK void * _Nonnull getTypeMetadata() {
    return &_impl::$sSuN;
  }
};

#pragma clang diagnostic pop

} // namespace swift

#endif
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-identifier"
namespace BlinkID SWIFT_PRIVATE_ATTR SWIFT_SYMBOL_MODULE("BlinkID") {


class AddressDetailedInfo { } SWIFT_UNAVAILABLE_MSG("Swift struct 'AddressDetailedInfo' cannot be represented in C++");

class AlphabetType { } SWIFT_UNAVAILABLE_MSG("Swift enum 'AlphabetType' cannot be represented in C++");

class BarcodeData { } SWIFT_UNAVAILABLE_MSG("Swift struct 'BarcodeData' cannot be represented in C++");

class BarcodeElementKey { } SWIFT_UNAVAILABLE_MSG("Swift enum 'BarcodeElementKey' cannot be represented in C++");

class BarcodeElements { } SWIFT_UNAVAILABLE_MSG("Swift struct 'BarcodeElements' cannot be represented in C++");

class BarcodeModuleSettings { } SWIFT_UNAVAILABLE_MSG("Swift struct 'BarcodeModuleSettings' cannot be represented in C++");

class BarcodeResult { } SWIFT_UNAVAILABLE_MSG("Swift struct 'BarcodeResult' cannot be represented in C++");

class BarcodeType { } SWIFT_UNAVAILABLE_MSG("Swift enum 'BarcodeType' cannot be represented in C++");

class BlinkIDSDK { } SWIFT_UNAVAILABLE_MSG("Swift struct 'BlinkIDSDK' cannot be represented in C++");

class BlinkIDScanningResult { } SWIFT_UNAVAILABLE_MSG("Swift struct 'BlinkIDScanningResult' cannot be represented in C++");

class BlinkIDSdk { } SWIFT_UNAVAILABLE_MSG("Swift class 'BlinkIDSdk' cannot be represented in C++");

class BlinkIDSdkSettings { } SWIFT_UNAVAILABLE_MSG("Swift struct 'BlinkIDSdkSettings' cannot be represented in C++");

class BlinkIDSession { } SWIFT_UNAVAILABLE_MSG("Swift class 'BlinkIDSession' cannot be represented in C++");

class BlinkIDSessionSettings { } SWIFT_UNAVAILABLE_MSG("Swift struct 'BlinkIDSessionSettings' cannot be represented in C++");

class BrowserDeviceInfoPinglet { } SWIFT_UNAVAILABLE_MSG("Swift struct 'BrowserDeviceInfoPinglet' cannot be represented in C++");

class CameraFrame { } SWIFT_UNAVAILABLE_MSG("Swift struct 'CameraFrame' cannot be represented in C++");

class CameraFrameVideoOrientation { } SWIFT_UNAVAILABLE_MSG("Swift enum 'CameraFrameVideoOrientation' cannot be represented in C++");

class CameraHardwareInfoPinglet { } SWIFT_UNAVAILABLE_MSG("Swift struct 'CameraHardwareInfoPinglet' cannot be represented in C++");

class CameraInputInfoPinglet { } SWIFT_UNAVAILABLE_MSG("Swift struct 'CameraInputInfoPinglet' cannot be represented in C++");

class CameraPermissionPinglet { } SWIFT_UNAVAILABLE_MSG("Swift struct 'CameraPermissionPinglet' cannot be represented in C++");

class CountryID { } SWIFT_UNAVAILABLE_MSG("Swift enum 'CountryID' cannot be represented in C++");

class CrashMonitor { } SWIFT_UNAVAILABLE_MSG("Swift class 'CrashMonitor' cannot be represented in C++");

class CroppedImageResult { } SWIFT_UNAVAILABLE_MSG("Swift struct 'CroppedImageResult' cannot be represented in C++");

// Unavailable in C++: Swift type alias 'DPI'.

class DataMatchFieldType { } SWIFT_UNAVAILABLE_MSG("Swift enum 'DataMatchFieldType' cannot be represented in C++");

class DataMatchResult { } SWIFT_UNAVAILABLE_MSG("Swift struct 'DataMatchResult' cannot be represented in C++");

class DataMatchState { } SWIFT_UNAVAILABLE_MSG("Swift enum 'DataMatchState' cannot be represented in C++");

template<class T_0_0>
#ifdef __cpp_concepts
requires swift::isUsableInGenericContext<T_0_0>
#endif // __cpp_concepts
class DateResult { } SWIFT_UNAVAILABLE_MSG("Swift generic struct 'DateResult' cannot be represented in C++");

class DependentInfo { } SWIFT_UNAVAILABLE_MSG("Swift struct 'DependentInfo' cannot be represented in C++");

class DetailedCroppedImageResult { } SWIFT_UNAVAILABLE_MSG("Swift struct 'DetailedCroppedImageResult' cannot be represented in C++");

class DetailedFieldType { } SWIFT_UNAVAILABLE_MSG("Swift struct 'DetailedFieldType' cannot be represented in C++");

class DetectionStatus { } SWIFT_UNAVAILABLE_MSG("Swift enum 'DetectionStatus' cannot be represented in C++");

class DocumentCaptureModuleSettings { } SWIFT_UNAVAILABLE_MSG("Swift struct 'DocumentCaptureModuleSettings' cannot be represented in C++");

class DocumentImageColorStatus { } SWIFT_UNAVAILABLE_MSG("Swift enum 'DocumentImageColorStatus' cannot be represented in C++");

class DocumentNumberRedactionSettings { } SWIFT_UNAVAILABLE_MSG("Swift struct 'DocumentNumberRedactionSettings' cannot be represented in C++");

class DocumentOrientation { } SWIFT_UNAVAILABLE_MSG("Swift enum 'DocumentOrientation' cannot be represented in C++");

class DocumentRotation { } SWIFT_UNAVAILABLE_MSG("Swift enum 'DocumentRotation' cannot be represented in C++");

class DocumentTypeID { } SWIFT_UNAVAILABLE_MSG("Swift enum 'DocumentTypeID' cannot be represented in C++");

template<class T_0_0>
#ifdef __cpp_concepts
requires swift::isUsableInGenericContext<T_0_0>
#endif // __cpp_concepts
class DriverLicenseDetailedInfo { } SWIFT_UNAVAILABLE_MSG("Swift generic struct 'DriverLicenseDetailedInfo' cannot be represented in C++");

class ErrorPinglet { } SWIFT_UNAVAILABLE_MSG("Swift struct 'ErrorPinglet' cannot be represented in C++");

class FieldState { } SWIFT_UNAVAILABLE_MSG("Swift struct 'FieldState' cannot be represented in C++");

class FieldType { } SWIFT_UNAVAILABLE_MSG("Swift enum 'FieldType' cannot be represented in C++");

class FrameProcessResult { } SWIFT_UNAVAILABLE_MSG("Swift struct 'FrameProcessResult' cannot be represented in C++");

class ImageAnalysisDetectionStatus { } SWIFT_UNAVAILABLE_MSG("Swift enum 'ImageAnalysisDetectionStatus' cannot be represented in C++");

class ImageAnalysisLightingStatus { } SWIFT_UNAVAILABLE_MSG("Swift enum 'ImageAnalysisLightingStatus' cannot be represented in C++");

class ImageExtractionType { } SWIFT_UNAVAILABLE_MSG("Swift enum 'ImageExtractionType' cannot be represented in C++");

class ImageOrientation { } SWIFT_UNAVAILABLE_MSG("Swift enum 'ImageOrientation' cannot be represented in C++");

class InputImage { } SWIFT_UNAVAILABLE_MSG("Swift class 'InputImage' cannot be represented in C++");

class InputImageCropAnalysis { } SWIFT_UNAVAILABLE_MSG("Swift enum 'InputImageCropAnalysis' cannot be represented in C++");

class InputImageCropType { } SWIFT_UNAVAILABLE_MSG("Swift enum 'InputImageCropType' cannot be represented in C++");

class InputImageResult { } SWIFT_UNAVAILABLE_MSG("Swift struct 'InputImageResult' cannot be represented in C++");

template<class T_0_0>
#ifdef __cpp_concepts
requires swift::isUsableInGenericContext<T_0_0>
#endif // __cpp_concepts
class InputImageResultProtocol { } SWIFT_UNAVAILABLE_MSG("protocol 'InputImageResultProtocol' can not yet be represented in C++");

class InputImageSelectionStrategy { } SWIFT_UNAVAILABLE_MSG("Swift enum 'InputImageSelectionStrategy' cannot be represented in C++");

class InputImageSource { } SWIFT_UNAVAILABLE_MSG("Swift enum 'InputImageSource' cannot be represented in C++");

class InvalidLicenseKeyError { } SWIFT_UNAVAILABLE_MSG("Swift struct 'InvalidLicenseKeyError' cannot be represented in C++");

class LogPinglet { } SWIFT_UNAVAILABLE_MSG("Swift struct 'LogPinglet' cannot be represented in C++");

class MRZDocumentType { } SWIFT_UNAVAILABLE_MSG("Swift enum 'MRZDocumentType' cannot be represented in C++");

class MRZResult { } SWIFT_UNAVAILABLE_MSG("Swift struct 'MRZResult' cannot be represented in C++");

class MemoryReserveError { } SWIFT_UNAVAILABLE_MSG("Swift struct 'MemoryReserveError' cannot be represented in C++");

class MissingBundle { } SWIFT_UNAVAILABLE_MSG("Swift struct 'MissingBundle' cannot be represented in C++");

class MissingResources { } SWIFT_UNAVAILABLE_MSG("Swift struct 'MissingResources' cannot be represented in C++");

class ModelLoadError { } SWIFT_UNAVAILABLE_MSG("Swift enum 'ModelLoadError' cannot be represented in C++");

class MrzModuleSettings { } SWIFT_UNAVAILABLE_MSG("Swift struct 'MrzModuleSettings' cannot be represented in C++");

class OTAResourceError { } SWIFT_UNAVAILABLE_MSG("Swift enum 'OTAResourceError' cannot be represented in C++");

class OTAResourcesConfig { } SWIFT_UNAVAILABLE_MSG("Swift struct 'OTAResourcesConfig' cannot be represented in C++");

template<class T_0_0>
#ifdef __cpp_concepts
requires swift::isUsableInGenericContext<T_0_0>
#endif // __cpp_concepts
class OtaSdkSettings { } SWIFT_UNAVAILABLE_MSG("protocol 'OtaSdkSettings' can not yet be represented in C++");

class OtaServiceURL { } SWIFT_UNAVAILABLE_MSG("Swift enum 'OtaServiceURL' cannot be represented in C++");

class ParentInfo { } SWIFT_UNAVAILABLE_MSG("Swift struct 'ParentInfo' cannot be represented in C++");

class PingManager { } SWIFT_UNAVAILABLE_MSG("Swift actor 'PingManager' cannot be represented in C++");

class PingStatus { } SWIFT_UNAVAILABLE_MSG("enum 'PingStatus' can not be represented in C++ as one of its cases has an associated value with type that can't be represented in C++");

template<class T_0_0>
#ifdef __cpp_concepts
requires swift::isUsableInGenericContext<T_0_0>
#endif // __cpp_concepts
class Pinglet { } SWIFT_UNAVAILABLE_MSG("protocol 'Pinglet' can not yet be represented in C++");

class Point { } SWIFT_UNAVAILABLE_MSG("Swift struct 'Point' cannot be represented in C++");

class ProcessingActor { } SWIFT_UNAVAILABLE_MSG("Swift actor 'ProcessingActor' cannot be represented in C++");

class ProcessingStatus { } SWIFT_UNAVAILABLE_MSG("Swift enum 'ProcessingStatus' cannot be represented in C++");

class Quadrilateral { } SWIFT_UNAVAILABLE_MSG("Swift struct 'Quadrilateral' cannot be represented in C++");

class RectangleF { } SWIFT_UNAVAILABLE_MSG("Swift struct 'RectangleF' cannot be represented in C++");

class RectangleFPoint { } SWIFT_UNAVAILABLE_MSG("Swift struct 'RectangleFPoint' cannot be represented in C++");

class RedactionMode { } SWIFT_UNAVAILABLE_MSG("Swift enum 'RedactionMode' cannot be represented in C++");

class RedactionSettings { } SWIFT_UNAVAILABLE_MSG("Swift struct 'RedactionSettings' cannot be represented in C++");

template<class T_0_0>
#ifdef __cpp_concepts
requires swift::isUsableInGenericContext<T_0_0>
#endif // __cpp_concepts
class RedactionSettingsResolver { } SWIFT_UNAVAILABLE_MSG("protocol 'RedactionSettingsResolver' can not yet be represented in C++");

class RegionID { } SWIFT_UNAVAILABLE_MSG("Swift enum 'RegionID' cannot be represented in C++");

class RegionOfInterest { } SWIFT_UNAVAILABLE_MSG("Swift struct 'RegionOfInterest' cannot be represented in C++");

class RequestTimeout { } SWIFT_UNAVAILABLE_MSG("Swift struct 'RequestTimeout' cannot be represented in C++");

class ResourceDownloaderError { } SWIFT_UNAVAILABLE_MSG("enum 'ResourceDownloaderError' can not be represented in C++ as one of its cases has an associated value with type that can't be represented in C++");

class ResourceLoadError { } SWIFT_UNAVAILABLE_MSG("Swift struct 'ResourceLoadError' cannot be represented in C++");

class ResourcesConfig { } SWIFT_UNAVAILABLE_MSG("Swift struct 'ResourcesConfig' cannot be represented in C++");

class ResourcesError { } SWIFT_UNAVAILABLE_MSG("Swift enum 'ResourcesError' cannot be represented in C++");

class SDKInitError { } SWIFT_UNAVAILABLE_MSG("Swift enum 'SDKInitError' cannot be represented in C++");

class ScanningConditionsPinglet { } SWIFT_UNAVAILABLE_MSG("Swift struct 'ScanningConditionsPinglet' cannot be represented in C++");

class ScanningMode { } SWIFT_UNAVAILABLE_MSG("Swift enum 'ScanningMode' cannot be represented in C++");

class ScanningSettings { } SWIFT_UNAVAILABLE_MSG("Swift struct 'ScanningSettings' cannot be represented in C++");

class ScanningSide { } SWIFT_UNAVAILABLE_MSG("Swift enum 'ScanningSide' cannot be represented in C++");

class SdkInitStartPinglet { } SWIFT_UNAVAILABLE_MSG("Swift struct 'SdkInitStartPinglet' cannot be represented in C++");

template<class T_0_0>
#ifdef __cpp_concepts
requires swift::isUsableInGenericContext<T_0_0>
#endif // __cpp_concepts
class SdkSettings { } SWIFT_UNAVAILABLE_MSG("protocol 'SdkSettings' can not yet be represented in C++");

class SensitivityLevel { } SWIFT_UNAVAILABLE_MSG("Swift enum 'SensitivityLevel' cannot be represented in C++");

class SessionError { } SWIFT_UNAVAILABLE_MSG("Swift enum 'SessionError' cannot be represented in C++");

class SettingsValidationError { } SWIFT_UNAVAILABLE_MSG("Swift struct 'SettingsValidationError' cannot be represented in C++");

class SingleSideScanningResult { } SWIFT_UNAVAILABLE_MSG("Swift struct 'SingleSideScanningResult' cannot be represented in C++");

class UXLicenseProviderBridge { } SWIFT_UNAVAILABLE_MSG("actor-isolated class 'UXLicenseProviderBridge' can not be exposed to C++");

class UxEventPinglet { } SWIFT_UNAVAILABLE_MSG("Swift struct 'UxEventPinglet' cannot be represented in C++");

class VIZResult { } SWIFT_UNAVAILABLE_MSG("Swift struct 'VIZResult' cannot be represented in C++");

template<class T_0_0>
#ifdef __cpp_concepts
requires swift::isUsableInGenericContext<T_0_0>
#endif // __cpp_concepts
class VehicleClassInfo { } SWIFT_UNAVAILABLE_MSG("Swift generic struct 'VehicleClassInfo' cannot be represented in C++");

class VizExtractionType { } SWIFT_UNAVAILABLE_MSG("Swift enum 'VizExtractionType' cannot be represented in C++");

class VizModuleSettings { } SWIFT_UNAVAILABLE_MSG("Swift struct 'VizModuleSettings' cannot be represented in C++");

class WrapperProductInfoPinglet { } SWIFT_UNAVAILABLE_MSG("Swift struct 'WrapperProductInfoPinglet' cannot be represented in C++");

} // namespace BlinkID

#pragma clang diagnostic pop
#undef SWIFT_SYMBOL
#endif
#pragma clang diagnostic pop
#endif
