name: Semgrep SAST Scan

on:
  push:
    branches:
      - master
  pull_request:
    branches: [ "master" ]
  schedule:
    # Run a full scan every Monday at midnight
    - cron: '0 0 * * 1'
  workflow_dispatch:

jobs:
  semgrep-android:
    name: Semgrep Scan (Android)
    runs-on: ubuntu-latest

    permissions:
      actions: read
      contents: read
      security-events: write

    container:
      image: semgrep/semgrep:1.171.0@sha256:bdf7013b2c3634a487671158da77c554f531742326b543a9464d2adf6c433ac8

    steps:
      - name: Checkout Code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          persist-credentials: false

      - name: Run Semgrep Scan
        run: >-
          semgrep scan
          --config p/security-audit
          --config p/secrets
          --config p/owasp-top-ten
          --config p/kotlin
          BlinkID/android
          --sarif
          --output=semgrep.sarif

      - name: Upload SARIF Results to GitHub Security Tab
        uses: github/codeql-action/upload-sarif@f205ea1c3313d32999d8d6a48b4f6530d4437b38 # v4.37.4
        if: always()
        with:
          sarif_file: semgrep.sarif
          category: semgrep-android

  semgrep-ios:
    name: Semgrep Scan (iOS)
    runs-on: ubuntu-latest

    permissions:
      actions: read
      contents: read
      security-events: write

    container:
      image: semgrep/semgrep:1.171.0@sha256:bdf7013b2c3634a487671158da77c554f531742326b543a9464d2adf6c433ac8

    steps:
      - name: Checkout Code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          persist-credentials: false

      - name: Run Semgrep Scan
        run: >-
          semgrep scan
          --config p/security-audit
          --config p/secrets
          --config p/owasp-top-ten
          --config p/swift
          BlinkID/ios
          --exclude BlinkID/ios/Frameworks
          --sarif
          --output=semgrep.sarif

      - name: Upload SARIF Results to GitHub Security Tab
        uses: github/codeql-action/upload-sarif@f205ea1c3313d32999d8d6a48b4f6530d4437b38 # v4.37.4
        if: always()
        with:
          sarif_file: semgrep.sarif
          category: semgrep-ios
